name: "\U0001F41B Bug Report"
description: Report an issue or possible bug
title: "[Bug] "
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report! Please fill out this form as completely as possible, it will help us address your problem more quickly.
  - type: input
    attributes:
      label: What version of `vite` are you using?
      placeholder: 0.0.0
    validations:
      required: true
  - type: textarea
    attributes:
      label: System info and storybook versions
      description: Please paste the results of `npx sb@next info` here.  If it doesn't include storybook versions, please add them as well.
      placeholder: |
        System:
          OS: macOS 12.3.1
          CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
        Binaries:
          Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
          Yarn: 1.22.17 - ~/.yarn/bin/yarn
          npm: 8.6.0 - ~/.nvm/versions/node/v16.4.0/bin/npm
        Browsers:
          Firefox: 99.0.1
          Safari: 15.4
        npmPackages:
          @storybook/addon-actions: ^6.4.22 => 6.4.22
          @storybook/addon-essentials: ^6.4.22 => 6.4.22
          @storybook/addon-interactions: ^6.4.22 => 6.4.22
          @storybook/addon-links: ^6.4.22 => 6.4.22
          @storybook/builder-vite: ^0.1.29 => 0.1.29
          @storybook/react: ^6.4.22 => 6.4.22
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.  What do you expect, vs what is happening?  Screenshots and logs are helpful as well.
    validations:
      required: true
  - type: input
    attributes:
      label: Link to Minimal Reproducible Example
      description: 'Use `npm create vite@latest` and then `npx sb@next init` to create a minimal reproduction of the problem, document any additional steps in README.md, and push up the repo to github.  We prioritize issues with reproductions over those without.'
      placeholder: 'https://github.com/ianvs/storybook-vite-issue-repro'
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Participation
      options:
        - label:  I am willing to submit a pull request for this issue.
          required: false
