name: Build Overview

on:
  push:
    branches:
      - main

jobs:
  examples:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Compile TypeScript
        run: yarn prepublish

      - name: Build examples
        run: yarn build-examples:overview

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
